# syntax=docker/dockerfile:1
# harness-hat base image — shared foundation for all language images.
# After modifying this file, rebuild with: hat rebuild
# (This also rebuilds every configured Dockerfile template that extends it.)

FROM rust:1.88-slim-bookworm AS tun2proxy-build

ENV GIT_HASH=crates-io

ARG TUN2PROXY_VERSION=0.7.21
RUN cargo install --locked --version "${TUN2PROXY_VERSION}" --bin tun2proxy-bin tun2proxy

# harness-hat base — Ubuntu 26.04 LTS (Resolute Raccoon)
#
# Build (context is the docker/ directory, matching the TUI's builder):
#   docker build -t harness-hat-base:local -f docker/harness-hat-base.dockerfile docker/
#
# Run command is generated by the harness-hat TUI for your project.
#
# ── Network filtering ─────────────────────────────────────────────────────────
# Harness Hat parses plain HTTP and gates HTTPS/raw TCP by CONNECT destination;
# TLS remains end-to-end and no private CA is injected into the container.

FROM ubuntu:26.04

# Capability marker used by the graphical launcher to reject/rebuild images
# created before Desktop SSH support was added.
LABEL dev.harness-hat.desktop-ssh="1"

ARG DEBIAN_FRONTEND=noninteractive
ARG UBUNTU_ARCHIVE_MIRRORS="http://archive.ubuntu.com/ubuntu/ http://us.archive.ubuntu.com/ubuntu/ http://mirrors.edge.kernel.org/ubuntu/ http://mirror.us.leaseweb.net/ubuntu/"
ARG UBUNTU_PORTS_MIRRORS="http://ports.ubuntu.com/ubuntu-ports/ http://mirror.us.leaseweb.net/ubuntu-ports/ http://mirrors.edge.kernel.org/ubuntu-ports/"

# Ubuntu archive and ports mirrors can be unreachable from some networks. Try a
# short list before the first package install and leave apt pointed at the first
# mirror that works.
RUN set -eu; \
    sources=/etc/apt/sources.list.d/ubuntu.sources; \
    upstream=; \
    mirrors=; \
    if grep -q 'http://ports.ubuntu.com/ubuntu-ports/' "$sources"; then \
      upstream='http://ports.ubuntu.com/ubuntu-ports/'; \
      mirrors="$UBUNTU_PORTS_MIRRORS"; \
    elif grep -q 'http://archive.ubuntu.com/ubuntu/' "$sources"; then \
      upstream='http://archive.ubuntu.com/ubuntu/'; \
      mirrors="$UBUNTU_ARCHIVE_MIRRORS"; \
    fi; \
    if [ -n "$upstream" ]; then \
      cp "$sources" /tmp/ubuntu.sources.orig; \
      selected_mirror=; \
      for mirror in $mirrors; do \
        sed \
          -e "s#${upstream}#${mirror}#g" \
          -e "s#http://security.ubuntu.com/ubuntu/#${mirror}#g" \
          /tmp/ubuntu.sources.orig > "$sources"; \
        rm -rf /var/lib/apt/lists/*; \
        if apt-get update -o APT::Update::Error-Mode=any; then \
          selected_mirror="$mirror"; \
          break; \
        fi; \
      done; \
      if [ -z "$selected_mirror" ]; then \
        cp /tmp/ubuntu.sources.orig "$sources"; \
        echo "No Ubuntu mirror worked from configured mirror list" >&2; \
        exit 1; \
      fi; \
      echo "Using Ubuntu mirror: $selected_mirror"; \
    fi

RUN apt-get update -o APT::Update::Error-Mode=any && apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      gnupg \
      nano \
      git \
      python3 \
      python3-pip \
      python3-venv \
      unzip \
      ripgrep \
      bubblewrap \
      htop \
      iproute2 \
      iptables \
      gosu \
      dbus-user-session \
      gnome-keyring \
      libsecret-tools \
      openssh-server \
      zsh \
    && rm -rf /var/lib/apt/lists/*

RUN install -d -m 0755 /run/sshd /etc/claude-code

# ast-grep: structural/AST-aware code search across all supported languages.
# Pinned release binary verified against sha256 from GitHub release assets.
ARG ASTGREP_VERSION=0.44.1
ARG ASTGREP_SHA256_AMD64=611f9e5e76f2611ecea1a35dd3468ceedf600641a11224b80341d79c6ee7b9dd
ARG ASTGREP_SHA256_AARCH64=077a4ab0c628154ef3cb79fecaf11dabca7f8a41f2c7260c022f263a52c1b021
ARG TARGETARCH
RUN set -eu; \
    case "${TARGETARCH:-$(dpkg --print-architecture)}" in \
        amd64|x86_64)  sg_arch="x86_64-unknown-linux-gnu";   sg_sha="${ASTGREP_SHA256_AMD64}" ;; \
        arm64|aarch64) sg_arch="aarch64-unknown-linux-gnu"; sg_sha="${ASTGREP_SHA256_AARCH64}" ;; \
        *) echo "unsupported ast-grep architecture: ${TARGETARCH:-$(dpkg --print-architecture)}" >&2; exit 1 ;; \
    esac; \
    curl -fsSL --retry 5 --retry-all-errors --retry-delay 2 \
        -o /tmp/sg.zip \
        "https://github.com/ast-grep/ast-grep/releases/download/${ASTGREP_VERSION}/app-${sg_arch}.zip"; \
    echo "${sg_sha}  /tmp/sg.zip" | sha256sum -c -; \
    unzip -q /tmp/sg.zip -d /tmp/sg-extract; \
    cp /tmp/sg-extract/sg /usr/local/bin/sg; \
    cp /tmp/sg-extract/ast-grep /usr/local/bin/ast-grep; \
    chmod 0755 /usr/local/bin/sg /usr/local/bin/ast-grep; \
    rm -rf /tmp/sg.zip /tmp/sg-extract; \
    sg --version

# oh-my-pi (omp): coding agent CLI. Pinned release binary verified against
# sha256 from the release's SHA256SUMS.txt.
ARG OMP_VERSION=17.2.15
ARG OMP_SHA256_AMD64=fa884941f932f4f5d2046acba971790ae6aae18fd4806472b01f041de670368a
ARG OMP_SHA256_ARM64=36507ba3d98332f52649d22009ead86f154ab007cb169d68690fa2b0111769ad
ARG TARGETARCH
RUN set -eu; \
    case "${TARGETARCH:-$(dpkg --print-architecture)}" in \
        amd64|x86_64)  omp_arch="x64";   omp_sha="${OMP_SHA256_AMD64}" ;; \
        arm64|aarch64) omp_arch="arm64"; omp_sha="${OMP_SHA256_ARM64}" ;; \
        *) echo "unsupported oh-my-pi architecture: ${TARGETARCH:-$(dpkg --print-architecture)}" >&2; exit 1 ;; \
    esac; \
    curl -fsSL --retry 5 --retry-all-errors --retry-delay 2 \
        -o /tmp/omp \
        "https://github.com/can1357/oh-my-pi/releases/download/v${OMP_VERSION}/omp-linux-${omp_arch}"; \
    echo "${omp_sha}  /tmp/omp" | sha256sum -c -; \
    install -m 0755 /tmp/omp /usr/local/bin/omp; \
    rm -f /tmp/omp; \
    omp --version

# Match Coder's conventional non-root user while keeping uid/gid 1000 for
# host-mounted auth and workspace files.
RUN set -eu; \
    if getent passwd ubuntu >/dev/null 2>&1; then \
      groupmod -n coder ubuntu; \
      usermod -l coder -d /home/coder -m -s /bin/zsh ubuntu; \
    elif ! getent passwd coder >/dev/null 2>&1; then \
      groupadd -g 1000 coder; \
      useradd -m -u 1000 -g 1000 -s /bin/zsh coder; \
    fi; \
    # Keep /home/ubuntu as a legacy alias for older configs and mounts.
    if [ ! -e /home/ubuntu ]; then \
      ln -s /home/coder /home/ubuntu; \
    fi

# Install a current Node runtime for common development CLIs.
# The NodeSource `nodejs` package already carries npm, and Ubuntu's `npm`
# package conflicts with it.
RUN set -eu; \
    mkdir -p /etc/apt/keyrings; \
    curl -fsSL --retry 5 --retry-all-errors --retry-delay 2 https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
      | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_24.x nodistro main" \
      > /etc/apt/sources.list.d/nodesource.list; \
    apt-get update -o APT::Update::Error-Mode=any && apt-get install -y --no-install-recommends nodejs \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/killme.py /usr/local/bin/killme
RUN sed -i 's/\r$//' /usr/local/bin/killme \
    && chmod 755 /usr/local/bin/killme
COPY --from=tun2proxy-build /usr/local/cargo/bin/tun2proxy-bin /usr/local/bin/tun2proxy-bin

RUN cat > /usr/local/bin/harness-hat-user-session.sh << 'SCRIPT'
#!/bin/sh
set -e

start_desktop_ssh() {
    authorized_key="${HARNESS_HAT_DESKTOP_SSH_AUTHORIZED_KEY:-}"
    [ -n "$authorized_key" ] || return 0

    ssh_dir="${HOME:-/home/coder}/.ssh"
    mkdir -p "$ssh_dir"
    chmod 700 "$ssh_dir"
    printf '%s\n' "$authorized_key" > "$ssh_dir/authorized_keys"
    chmod 600 "$ssh_dir/authorized_keys"

    # sshd constructs a fresh login environment instead of inheriting the
    # container's. Preserve the environment Hat already supplied so the SSH
    # session keeps its scoped control token/proxy and template toolchain PATH.
    # Docker env-file values are single-line; defensively skip anything else.
    python3 - "$ssh_dir/environment" <<'PY'
import os
import sys

with open(sys.argv[1], "w", encoding="utf-8") as output:
    for name, value in sorted(os.environ.items()):
        if "\n" not in name and "=" not in name and "\n" not in value and "\r" not in value:
            output.write(f"{name}={value}\n")
PY
    chmod 600 "$ssh_dir/environment"

    host_key="$ssh_dir/harness-hat-desktop-host-key"
    if [ ! -f "$host_key" ]; then
        ssh-keygen -q -t ed25519 -N '' -f "$host_key"
    fi
    chmod 600 "$host_key"

    config="$ssh_dir/harness-hat-desktop-sshd_config"
    cat > "$config" <<EOF
Port 2222
ListenAddress 0.0.0.0
HostKey $host_key
PidFile $ssh_dir/harness-hat-desktop-sshd.pid
AuthorizedKeysFile $ssh_dir/authorized_keys
AuthenticationMethods publickey
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
UsePAM no
AllowUsers coder
AllowAgentForwarding no
AllowTcpForwarding local
GatewayPorts no
X11Forwarding no
PermitTunnel no
PermitUserEnvironment yes
Subsystem sftp internal-sftp
EOF
    chmod 600 "$config"

    /usr/sbin/sshd -D -e -f "$config" > "$ssh_dir/harness-hat-desktop-sshd.log" 2>&1 &
    sshd_pid=$!
    sleep 0.2
    if ! kill -0 "$sshd_pid" 2>/dev/null; then
        echo "harness-hat: Claude Desktop SSH service failed to start" >&2
        cat "$ssh_dir/harness-hat-desktop-sshd.log" >&2 || true
        exit 1
    fi
}

if [ -z "${XDG_RUNTIME_DIR:-}" ]; then
    XDG_RUNTIME_DIR="/tmp/harness-hat-runtime-$(id -u)"
    export XDG_RUNTIME_DIR
fi
mkdir -p "$XDG_RUNTIME_DIR"
chmod 700 "$XDG_RUNTIME_DIR" 2>/dev/null || true

if command -v gnome-keyring-daemon >/dev/null 2>&1; then
    # Antigravity CLI stores auth tokens in the Linux Secret Service. In this
    # headless container there is no desktop login manager to start/unlock it.
    # An empty-password keyring is acceptable here because its files live in the
    # user's Harness Hat state directory on the host, not in the host OS keyring.
    eval "$(printf '\n' | gnome-keyring-daemon --unlock --components=secrets 2>/dev/null || true)"
fi

start_desktop_ssh

exec "$@"
SCRIPT
RUN sed -i 's/\r$//' /usr/local/bin/harness-hat-user-session.sh \
    && chmod 755 /usr/local/bin/harness-hat-user-session.sh

RUN cat > /usr/local/bin/harness-hat-init.sh << 'SCRIPT'
#!/bin/sh
set -e

seed_codex_state() {
    source_dir="${HARNESS_HAT_CODEX_SEED:-}"
    [ -n "$source_dir" ] && [ -d "$source_dir" ] || return 0

    target_dir="${HOME:-/home/coder}/.codex"
    mkdir -p "$target_dir"

    # Codex's SQLite databases and runtime caches must remain on the Linux
    # filesystem. Copy only portable state from the host; auth refreshes and
    # other writes then land in this container's private Docker volume.
    for entry in \
        auth.json \
        config.toml \
        installation_id \
        version.json \
        rules \
        skills \
        plugins
    do
        if [ -e "$source_dir/$entry" ]; then
            rm -rf "$target_dir/$entry"
            cp -R "$source_dir/$entry" "$target_dir/$entry"
        fi
    done

    if [ "$(id -u)" = "0" ]; then
        chown -R 1000:1000 "$target_dir"
    fi
}

seed_codex_state

start_localhost_forwards() {
    HH_LOCALHOST_FORWARDS="${HARNESS_HAT_LOCALHOST_FORWARDS:-}"
    [ -n "$HH_LOCALHOST_FORWARDS" ] || return 0
    HH_LOCALHOST_FORWARD_HOST="${HARNESS_HAT_LOCALHOST_FORWARD_HOST:-host.docker.internal}"
    HH_LOCALHOST_FORWARD_TARGET="$(getent ahostsv4 "$HH_LOCALHOST_FORWARD_HOST" 2>/dev/null | awk '{print $1; exit}')"
    [ -n "$HH_LOCALHOST_FORWARD_TARGET" ] || HH_LOCALHOST_FORWARD_TARGET="$HH_LOCALHOST_FORWARD_HOST"
    python3 - "$HH_LOCALHOST_FORWARDS" "$HH_LOCALHOST_FORWARD_TARGET" <<'PY' &
import select
import socket
import sys
import threading

spec_arg = sys.argv[1]
target_host = sys.argv[2]


def parse_port(value):
    try:
        port = int(value)
    except ValueError as exc:
        raise ValueError(f"invalid port {value!r}") from exc
    if port < 1 or port > 65535:
        raise ValueError(f"port out of range: {port}")
    return port


forwards = []
for raw in spec_arg.split(","):
    raw = raw.strip()
    if not raw:
        continue
    if ":" in raw:
        container_port_raw, host_port_raw = raw.split(":", 1)
    else:
        container_port_raw = host_port_raw = raw
    forwards.append((parse_port(container_port_raw), parse_port(host_port_raw)))

if not forwards:
    sys.exit(0)


def relay(client, host_port):
    upstream = None
    try:
        upstream = socket.create_connection((target_host, host_port), timeout=10)
        client.setblocking(False)
        upstream.setblocking(False)
        sockets = [client, upstream]
        while True:
            readable, _, _ = select.select(sockets, [], [], 60)
            for sock in readable:
                data = sock.recv(65536)
                if not data:
                    return
                (upstream if sock is client else client).sendall(data)
    except Exception as exc:
        print(f"harness-hat: localhost forward connection failed: {exc}", file=sys.stderr)
    finally:
        for sock in (client, upstream):
            if sock is not None:
                try:
                    sock.close()
                except OSError:
                    pass


def listen(sock, bind_host, container_port, host_port):
    print(
        f"harness-hat: forwarding {bind_host}:{container_port} to {target_host}:{host_port}",
        file=sys.stderr,
        flush=True,
    )
    while True:
        client, _ = sock.accept()
        threading.Thread(target=relay, args=(client, host_port), daemon=True).start()


listeners = []
for container_port, host_port in forwards:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind(("127.0.0.1", container_port))
    sock.listen(128)
    listeners.append((sock, "127.0.0.1", container_port, host_port))

    try:
        sock6 = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
        sock6.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock6.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
        sock6.bind(("::1", container_port))
        sock6.listen(128)
        listeners.append((sock6, "::1", container_port, host_port))
    except OSError as exc:
        print(
            f"harness-hat: warning: could not bind ::1:{container_port}: {exc}",
            file=sys.stderr,
            flush=True,
        )

for sock, bind_host, container_port, host_port in listeners:
    threading.Thread(
        target=listen,
        args=(sock, bind_host, container_port, host_port),
        daemon=True,
    ).start()

threading.Event().wait()
PY
    HH_LOCALHOST_FORWARD_PID=$!
    sleep 0.2
    if ! kill -0 "$HH_LOCALHOST_FORWARD_PID" 2>/dev/null; then
        echo "harness-hat: localhost forward setup failed" >&2
        exit 1
    fi
}

start_localhost_forwards

# Optional: strict network enforcement.
# TUN mode captures outbound TCP at the routing layer and forwards it through
# the harness-hat scoped HTTP proxy via tun2proxy.  This does not rely on the
# application honoring HTTP(S)_PROXY or ALL_PROXY.  UDP/QUIC are intentionally
# blocked; DNS to Docker's embedded resolver is allowed.
if [ "${HARNESS_HAT_STRICT_NETWORK:-0}" = "1" ]; then
    if [ "$(id -u)" != "0" ]; then
        echo "harness-hat: strict_network requires root" >&2
        exit 1
    fi
    if [ -z "${HARNESS_HAT_SCOPED_PROXY_ADDR:-}" ] || [ -z "${HARNESS_HAT_SCOPED_PROXY_AUTH:-}" ] || [ -z "${HARNESS_HAT_URL:-}" ]; then
        echo "harness-hat: strict_network missing HARNESS_HAT_SCOPED_PROXY_ADDR, HARNESS_HAT_SCOPED_PROXY_AUTH, or HARNESS_HAT_URL" >&2
        exit 1
    fi

    if [ ! -c /dev/net/tun ]; then
        echo "harness-hat: strict_network requires /dev/net/tun (Docker Desktop usually needs --privileged)" >&2
        exit 1
    fi

    # ── Pick the iptables binary that actually works ──────────────────────
    # Ubuntu 26.04 defaults to iptables-nft.  Docker Desktop's LinuxKit VM
    # may only support iptables-legacy.  Probe both and use the first that
    # succeeds at listing the filter/OUTPUT chain.
    IPT=""
    IP6T=""
    for candidate in iptables-legacy iptables; do
        if command -v "$candidate" >/dev/null 2>&1 \
           && "$candidate" -w -t filter -L OUTPUT -n >/dev/null 2>&1; then
            IPT="$candidate"
            break
        fi
    done
    for candidate in ip6tables-legacy ip6tables; do
        if command -v "$candidate" >/dev/null 2>&1 \
           && "$candidate" -w -t filter -L OUTPUT -n >/dev/null 2>&1; then
            IP6T="$candidate"
            break
        fi
    done
    if [ -z "$IPT" ]; then
        echo "harness-hat: strict_network requires a working iptables (tried iptables-legacy, iptables)" >&2
        exit 1
    fi

    proxy_host="${HARNESS_HAT_SCOPED_PROXY_ADDR%:*}"
    proxy_port="${HARNESS_HAT_SCOPED_PROXY_ADDR##*:}"
    proxy_conn_limit="${HARNESS_HAT_PROXY_CONN_LIMIT:-0}"
    case "$proxy_conn_limit" in
        ''|*[!0-9]*) proxy_conn_limit=0 ;;
    esac
    control_hostport="$(printf '%s' "$HARNESS_HAT_URL" | sed -E 's#^[a-zA-Z]+://##')"
    control_scheme="$(printf '%s' "$HARNESS_HAT_URL" | sed -E 's#^([a-zA-Z]+)://.*#\1#')"
    [ -n "$control_scheme" ] || control_scheme="http"
    control_host="${control_hostport%:*}"
    control_port="${control_hostport##*:}"

    proxy_ip="$(getent ahostsv4 "$proxy_host" 2>/dev/null | awk '{print $1; exit}')"
    control_ip="$(getent ahostsv4 "$control_host" 2>/dev/null | awk '{print $1; exit}')"
    forward_host="${HARNESS_HAT_LOCALHOST_FORWARD_HOST:-host.docker.internal}"
    forward_ip=""
    if [ -n "${HARNESS_HAT_LOCALHOST_FORWARDS:-}" ]; then
        forward_ip="$(getent ahostsv4 "$forward_host" 2>/dev/null | awk '{print $1; exit}')"
    fi
    if [ -z "$proxy_ip" ] || [ -z "$control_ip" ]; then
        echo "harness-hat: strict_network failed to resolve proxy ($proxy_host) or control ($control_host) hosts" >&2
        exit 1
    fi
    if [ -n "${HARNESS_HAT_LOCALHOST_FORWARDS:-}" ] && [ -z "$forward_ip" ]; then
        echo "harness-hat: strict_network failed to resolve localhost forward host ($forward_host)" >&2
        exit 1
    fi

    # Keep lifecycle control traffic on the direct control-server path.
    # In strict mode with virtual DNS, hostnames can resolve to synthetic
    # 198.18.0.0/15 addresses; using the resolved bridge IP avoids that.
    export HARNESS_HAT_URL="${control_scheme}://${control_ip}:${control_port}"

    echo "harness-hat: strict_network using $IPT; proxy=$proxy_ip:$proxy_port control=$control_ip:$control_port proxy_conn_limit=$proxy_conn_limit" >&2
    # ── Layer 1: strict egress filter ────────────────────────────────────
    # Allow only: loopback, tun0 (captured traffic), established/related,
    # Docker DNS, proxy, control server, and configured localhost forwards. Traffic
    # written to tun0 is not raw egress;
    # tun2proxy consumes it in userspace and opens the real upstream sockets.
    # Anything escaping that path on a physical interface is rejected here.
    $IPT -w -t filter -N HH_EGRESS 2>/dev/null || $IPT -w -t filter -F HH_EGRESS
    $IPT -w -t filter -C OUTPUT -j HH_EGRESS 2>/dev/null || $IPT -w -t filter -I OUTPUT 1 -j HH_EGRESS
    $IPT -w -t filter -F HH_EGRESS
    $IPT -w -t filter -A HH_EGRESS -o lo -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -o tun0 -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -p udp -d 127.0.0.11 --dport 53 -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -p tcp -d 127.0.0.11 --dport 53 -j ACCEPT
    if [ "$proxy_conn_limit" -gt 0 ]; then
        if ! $IPT -w -t filter -A HH_EGRESS -p tcp -d "$proxy_ip" --dport "$proxy_port" \
            -m connlimit --connlimit-above "$proxy_conn_limit" --connlimit-mask 32 \
            -j REJECT 2>/dev/null; then
            echo "harness-hat: warning: iptables connlimit unavailable; scoped proxy socket cap disabled" >&2
        fi
    fi
    $IPT -w -t filter -A HH_EGRESS -p tcp -d "$proxy_ip" --dport "$proxy_port" -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -p tcp -d "$control_ip" --dport "$control_port" -j ACCEPT
    if [ -n "${HARNESS_HAT_LOCALHOST_FORWARDS:-}" ]; then
        old_ifs="$IFS"
        IFS=','
        for spec in $HARNESS_HAT_LOCALHOST_FORWARDS; do
            host_port="${spec#*:}"
            [ "$host_port" != "$spec" ] || host_port="$spec"
            case "$host_port" in
                ''|*[!0-9]*)
                    echo "harness-hat: invalid localhost forward spec: $spec" >&2
                    exit 1
                    ;;
            esac
            $IPT -w -t filter -A HH_EGRESS -p tcp -d "$forward_ip" --dport "$host_port" -j ACCEPT
        done
        IFS="$old_ifs"
    fi
    $IPT -w -t filter -A HH_EGRESS -j REJECT 2>/dev/null || $IPT -w -t filter -A HH_EGRESS -j DROP

    # IPv6: reject everything to avoid long hangs on AAAA/QUIC attempts.
    if [ -n "$IP6T" ]; then
        $IP6T -w -t filter -N HH_EGRESS 2>/dev/null || $IP6T -w -t filter -F HH_EGRESS
        $IP6T -w -t filter -C OUTPUT -j HH_EGRESS 2>/dev/null || $IP6T -w -t filter -I OUTPUT 1 -j HH_EGRESS
        $IP6T -w -t filter -F HH_EGRESS
        $IP6T -w -t filter -A HH_EGRESS -o lo -j ACCEPT
        $IP6T -w -t filter -A HH_EGRESS -o tun0 -j ACCEPT
        $IP6T -w -t filter -A HH_EGRESS -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
        $IP6T -w -t filter -A HH_EGRESS -j REJECT 2>/dev/null || $IP6T -w -t filter -A HH_EGRESS -j DROP
    fi

    # ── Layer 2: tun2proxy routing ───────────────────────────────────────
    # Bypass the scoped proxy and control server addresses so tun2proxy can talk
    # to them directly.  Docker's DNS (127.0.0.11) remains reachable.
    TUN2PROXY_BIN="$(command -v tun2proxy-bin 2>/dev/null || true)"
    if [ -z "$TUN2PROXY_BIN" ]; then
        for candidate in \
            /usr/local/bin/tun2proxy-bin \
            /usr/local/cargo/bin/tun2proxy-bin \
            /root/.cargo/bin/tun2proxy-bin
        do
            if [ -x "$candidate" ]; then
                TUN2PROXY_BIN="$candidate"
                break
            fi
        done
    fi
    if [ -z "$TUN2PROXY_BIN" ]; then
        echo "harness-hat: tun2proxy-bin not found in PATH or common cargo locations" >&2
        exit 1
    fi
    if [ -n "$forward_ip" ]; then
        "$TUN2PROXY_BIN" \
            --setup \
            --proxy "http://harness-hat:${HARNESS_HAT_SCOPED_PROXY_AUTH}@${proxy_ip}:${proxy_port}" \
            --dns virtual \
            --bypass "$proxy_ip" \
            --bypass "$control_ip" \
            --bypass "$forward_ip" \
            >/tmp/harness-hat-tun2proxy.log 2>&1 &
    else
        "$TUN2PROXY_BIN" \
            --setup \
            --proxy "http://harness-hat:${HARNESS_HAT_SCOPED_PROXY_AUTH}@${proxy_ip}:${proxy_port}" \
            --dns virtual \
            --bypass "$proxy_ip" \
            --bypass "$control_ip" \
            >/tmp/harness-hat-tun2proxy.log 2>&1 &
    fi
    HH_TUN2PROXY_PID=$!
    sleep 1
    if ! kill -0 "$HH_TUN2PROXY_PID" 2>/dev/null; then
        echo "harness-hat: tun2proxy failed to start" >&2
        cat /tmp/harness-hat-tun2proxy.log >&2 || true
        exit 1
    fi

    # With TUN capture active, application-level proxy env vars are not needed
    # and can cause double-proxying in clients that partially support them.
    unset HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
    unset http_proxy https_proxy all_proxy no_proxy

    echo "harness-hat: strict_network ready (tun2proxy + iptables filter)" >&2
fi

clear 2>/dev/null || true

if [ "$(id -u)" = "0" ]; then
    exec gosu 1000:1000 dbus-run-session -- /usr/local/bin/harness-hat-user-session.sh "$@"
fi
exec dbus-run-session -- /usr/local/bin/harness-hat-user-session.sh "$@"
SCRIPT
RUN sed -i 's/\r$//' /usr/local/bin/harness-hat-init.sh \
    && chmod 755 /usr/local/bin/harness-hat-init.sh

# npm registry packages are integrity-checked by npm against the registry
# metadata; pinning the versions (H5) makes the build reproducible and stops a
# newly-published malicious release from entering the image silently. Bump by
# editing the ARGs and rebuilding.
ARG CODEX_CLI_VERSION=0.144.0
ARG PI_CODING_AGENT_VERSION=0.80.5
RUN npm install -g \
    "@openai/codex@${CODEX_CLI_VERSION}" \
    "@earendil-works/pi-coding-agent@${PI_CODING_AGENT_VERSION}"

ARG TARGETARCH
ARG ANTIGRAVITY_CLI_VERSION=1.0.6
RUN set -eu; \
    case "${TARGETARCH:-$(dpkg --print-architecture)}" in \
      amd64|x86_64) agy_arch="x64"; agy_sha="3eae552781d3054b782142e3cfe7be73e3bd068c736a432ca6f1adaa40f19e07" ;; \
      arm64|aarch64) agy_arch="arm64"; agy_sha="be6303d4b891a79457ca6ed169aff2efd3ceb694354634e85ef58c883bae6739" ;; \
      *) echo "unsupported Antigravity CLI architecture: ${TARGETARCH:-$(dpkg --print-architecture)}" >&2; exit 1 ;; \
    esac; \
    curl -fsSL --retry 5 --retry-all-errors --retry-delay 2 \
      -o /tmp/agy_cli_linux.tar.gz \
      "https://github.com/google-antigravity/antigravity-cli/releases/download/${ANTIGRAVITY_CLI_VERSION}/agy_cli_linux_${agy_arch}.tar.gz"; \
    echo "${agy_sha}  /tmp/agy_cli_linux.tar.gz" | sha256sum -c -; \
    tar -xzf /tmp/agy_cli_linux.tar.gz -C /usr/local/bin antigravity; \
    ln -sf /usr/local/bin/antigravity /usr/local/bin/agy; \
    chmod 755 /usr/local/bin/antigravity; \
    rm -f /tmp/agy_cli_linux.tar.gz; \
    test -x /usr/local/bin/antigravity; \
    test -x /usr/local/bin/agy

# jq — required by the default Claude Code statusLine script
# (~/.claude/statusline-command.sh parses the status JSON via jq) and broadly
# useful for in-container tooling.
RUN apt-get update -o APT::Update::Error-Mode=any \
    && apt-get install -y --no-install-recommends jq \
    && rm -rf /var/lib/apt/lists/*

# Claude Code comes from Anthropic's signed stable apt repository. Avoid the
# mutable `install.sh latest` path: it made otherwise identical image rebuilds
# execute unpinned remote code and produce different binaries.
RUN set -eu; \
    install -d -m 0755 /etc/apt/keyrings; \
    curl -fsSL --retry 5 --retry-all-errors --retry-delay 2 https://downloads.claude.ai/keys/claude-code.asc \
      -o /etc/apt/keyrings/claude-code.asc; \
    echo "deb [signed-by=/etc/apt/keyrings/claude-code.asc] https://downloads.claude.ai/claude-code/apt/stable stable main" \
      > /etc/apt/sources.list.d/claude-code.list; \
    apt-get update -o APT::Update::Error-Mode=any \
    && apt-get install -y --no-install-recommends claude-code \
    && rm -rf /var/lib/apt/lists/* \
    && ln -sf /usr/bin/claude /usr/local/bin/claude-stable
ENV DISABLE_AUTOUPDATER=1

# Coder-compatible user at uid/gid 1000.
USER coder
RUN mkdir -p /home/coder/.local/bin /home/coder/.codex \
    && printf '#!/bin/sh\nexec claude --dangerously-skip-permissions "$@"\n' \
       > /home/coder/.local/bin/claude-yolo \
    && printf '#!/bin/sh\nexec codex --yolo "$@"\n' \
       > /home/coder/.local/bin/codex-yolo \
    && printf '#!/bin/sh\nexec agy --dangerously-skip-permissions "$@"\n' \
       > /home/coder/.local/bin/agy-yolo \
    && printf '#!/bin/sh\nexec omp --yolo "$@"\n' \
       > /home/coder/.local/bin/omp-yolo \
    && chmod 755 /home/coder/.local/bin/claude-yolo \
                 /home/coder/.local/bin/codex-yolo \
                 /home/coder/.local/bin/agy-yolo \
                 /home/coder/.local/bin/omp-yolo

# Minimal zshrc: per-workspace history, seeded once from the host's own
# history (bind-mounted read-only at ~/.zsh_history.host, see
# shared_session_state_mounts) so a fresh workspace starts with the commands
# you already know instead of an empty file. After the first run, HISTFILE
# stays pointed at the workspace-local copy — the host file is never written
# to, so there's no risk of container sessions corrupting your live shell
# history or racing with it.
RUN cat > /home/coder/.zshrc <<'EOF'
HISTFILE="/workspace/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY APPEND_HISTORY HIST_IGNORE_DUPS

if [ ! -e "$HISTFILE" ] && [ -r "$HOME/.zsh_history.host" ]; then
    cp "$HOME/.zsh_history.host" "$HISTFILE" 2>/dev/null || true
fi
EOF

# Oh My Zsh with git plugin. Pin both the source revision and archive hash so
# image builds never execute mutable remote installer code.
ARG OH_MY_ZSH_COMMIT=59a9740721b734835812121322d6fe4827b0853a
ARG OH_MY_ZSH_SHA256=897a7ffb6bbf96b1f2914eb3da37c774cbd72be5f73242c568be7807dd2967e8
RUN set -eu; \
    curl -fsSL --retry 5 --retry-all-errors --retry-delay 2 \
        -o /tmp/oh-my-zsh.tar.gz \
        "https://github.com/ohmyzsh/ohmyzsh/archive/${OH_MY_ZSH_COMMIT}.tar.gz"; \
    echo "${OH_MY_ZSH_SHA256}  /tmp/oh-my-zsh.tar.gz" | sha256sum -c -; \
    mkdir -p /home/coder/.oh-my-zsh; \
    tar -xzf /tmp/oh-my-zsh.tar.gz --strip-components=1 -C /home/coder/.oh-my-zsh; \
    rm -f /tmp/oh-my-zsh.tar.gz; \
    printf '%s\n' \
        'ZSH=/home/coder/.oh-my-zsh' \
        'ZSH_THEME="robbyrussell"' \
        'plugins=(git)' \
        'source "$ZSH/oh-my-zsh.sh"' \
        >> /home/coder/.zshrc

# Keep user-installed tools and the bundled wrappers ahead of system paths.
ENV PATH="/home/coder/.local/bin:${PATH}"
WORKDIR /workspace

ENTRYPOINT ["/usr/local/bin/harness-hat-init.sh"]
CMD ["/bin/zsh"]
